### ISSUE TITLE
There is a authentification problem in ADRealm and Mailarchivaprincipal

### ISSUE THREAD

**Issue by sinramyeon** [k4200/openmailarchiva-server#17]
Dear Kazuso san, and Dear friends.

Hello. I'm a developer who do mailarchiva-related programming in korea.
Now we're updating lucene 2.9.4 to 6.4.2 in mailarchiva.

But there is crucial bug in login.

When I log in by admin, through ADRealm, and Mailarchivaprincipal
The code never reaches to ADRealm.IsUserinRole().

Found Successfully authetificated by admin / master User, but never found Role "Search" and go to method "isUserinRole".

If someone got a hint for this bug, please give your hand.

Thanks.

**Comment by k4200** [comment]
Hi,

> Now we're updating lucene 2.9.4 to 6.4.2 in mailarchiva.
> 
> But there is crucial bug in login.

I have a couple of questions.

1. Were you able to log in before updating Lucene?
2. Are there any error messages in the log file?

Thanks.

**Comment by sinramyeon** [comment]
Hello,

Firstly Thank you for your concern.

The thing is...
1. Yes, It was available at 2.9.4 or old version. I've tried several version in 2.xx
    Later I should try more with another version somehow...
2. No, there is no log. Page just pass me through to "searchform.do" but i still see the login.do view.


I've debugged somehow and I found when we use 2.xx, Login method goes firstly ADRealm and goes authenticateMaster -> log successfully, and goes MailArchivaPrincipal to create MailArchivaPrincipal().
I found it creates MailArchivaPrincipal with admin, master but goes to MailARchivaPrincipal.getName() and never returns a result.

Actually It returns name and next ADRealm.isUserInRole is activate.
But when i use lucene 6.xx version, it never goes to isUserInRole, and just stop at MailARchivaPrincipal.getName(I'm trying to figure out what ohter method is running after.)

It's really complicated bug, and I couldn't find lucene 6.xx things on web easily,
Asked at qiita, sourceforge, stackoverflow but there were no answer and i still can't figure out what's the problem...

If you have any idea, your help your help will be greatly appreciated.
Appreciate all of your support.

**Comment by k4200** [comment]
Sorry for this late reply.

> No, there is no log.

I'm not sure what you meant by this, but you could add debug logging to see what's happening. The log files are stored in `/usr/local/mailarchiva/server/logs/` (in Linux).

I haven't tried Lucene 6.x with MailArchiva, but there must be incompatible changes, so even if you fix this issue, I guess you'll have other ones as well.

**Comment by k4200** [comment]
Closing since the issue has been fixed. Quoted from issue #18 
> Luckily I'm figured out login problem..

@hero0926 
It would be great if you could tell us what the problem was. Thanks.
